💫Update (Add aws_eksctl_tool function for EKSCTL installation)

diff --git a/ktool b/ktool
--- a/ktool
+++ b/ktool
@@ -2197,9 +2197,40 @@ function aws_tools() {
 	aws_cli_tools
 }
 
+function aws_eksctl_tool() {
+	echo -e "AWS Official Documentation: 
+    'https://docs.aws.amazon.com/eks/latest/eksctl/installation.html'
+    "
+    which eksctl > /dev/null 2>&1
+    [ $? -eq 0 ] && echo -e "
+    +-------------------------------------------------------+
+    |${MAGENTA}AWS EKSCTL is already installed${ENDCOLOR}
+    +-------------------------------------------------------+
+    " && exit $? \
+    || echo -e "
+    +-------------------------------------------------------+
+    |${MAGENTA}Installing AWS EKSCTL${ENDCOLOR}
+    +-------------------------------------------------------+
+    "
+	# for ARM systems, set ARCH to: `arm64`, `armv6` or `armv7`
+	ARCH=amd64
+	PLATFORM=$(uname -s)_$ARCH
+	curl -LO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"
+	# (Optional) Verify checksum
+	# curl -sL "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_checksums.txt" | grep $PLATFORM | sha256sum --check
+	tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz
+	sudo install -m 0755 /tmp/eksctl /usr/local/bin && rm /tmp/eksctl
+ 	[ $? -eq 0 ] && echo -e "
+    +-------------------------------------------------------+
+    |${GREEN}AWS EKSCTL CLI installed successfully${ENDCOLOR}
+    +-------------------------------------------------------+
+    " && exit $?
+}
+
 function aws_cli_tools(){
     # ASW CLI Tools
     echo "1. Install AWS CLI v2"
+ 	echo "2. Install AWS EKSCTL"
     read option
     case $option in
     1)
@@ -2228,8 +2259,11 @@ function aws_cli_tools(){
             +-------------------------------------------------------+
             " && exit $?
         ;;
+	2)
+		aws_eksctl_tool
+		;;
     *)
-         echo "Invalid choice. Please select 1 to 5."
+         echo "Invalid choice. Please select 1 to 2."
         ;;
     esac
 }
